@startuml

class NetworkManager {
    +bool IsServer
    +bool IsClient
    +bool IsHost
    +List<NetworkClient> ConnectedClients
    
    +void StartServer()
    +void StartClient()
    +void StartHost()
    +void Shutdown()
}

class NetworkObject {
    + Spawn() : void
    + Despawn() : void
    + GetNetworkID(): int
    - mIsOwner: bool
    - mNetworkID: int
}

class NetworkBehaviour {
    +void ServerRpc()
    +void ClientRpc()
    + {abstract} OnNetworkSpawn()
    
}

' Template class for network variables
class NetworkVariable{
    + NetworkVariable(WritePermission)
    + T Value
    
}

class MonoBehavior{}

' Maybe not needed
class NetworkTransform {
    + UpdateTransform()
    + SyncPosition()
    + Interpolate()
}

class Transform{}

class NetworkClient {
    + ConnectToServer()
    + SendInputToServer()
    + ReceiveGameState()

    - mIsConnected: bool
    - mClientID: int
}

class NetworkServer {
    + HandleClientConnection()
    + ValidateInput()
    + SendGameState()
}

class NetworkHost {
    + ActAsClient()
    + ActAsServer()
}

' class NetworkMessage {
'     + Serialize()
'     + Deserialize()
'     + SendMessage()
'     - mMessageType: string
' }

class NetworkSceneManager {
    + LoadScene()
    + SyncScene()
    + UnloadScene()
}

' class NetworkInputManager {
'     + CaptureInput()
'     + SendInput()
'     + ApplyInputPrediction()
' }

' class NetworkReplicationManager {
'     + ReplicateObjectState()
'     + SyncWithClients()
'     + ApplyInterpolation()
' }

' class AuthorityManager {
'     + AssignAuthority()
'     + RequestControl()
'     - mObjectAuthority: string
' }

class INetworkSerializable {
    + {abstract} NetworkSerialize()
    ' + Deserialize()
}

NetworkManager <-- NetworkClient
NetworkManager <-- NetworkServer
NetworkManager <-- NetworkHost
NetworkManager *-- NetworkSceneManager
NetworkManager *-- "1" NetworkObject
' NetworkManager <-- AuthorityManager

NetworkObject *-- "*" NetworkBehaviour
NetworkBehaviour <-- NetworkTransform
NetworkBehaviour --|> MonoBehavior

NetworkTransform --|> Transform

' NetworkClient --> NetworkInputManager
' NetworkClient --> NetworkMessage
' NetworkClient --> NetworkReplicationManager

' NetworkServer --> NetworkMessage
' NetworkServer --> NetworkReplicationManager


NetworkHost <-- NetworkServer
NetworkHost <-- NetworkClient

' AuthorityManager <-- NetworkObject
NetworkSceneManager *-- "*" NetworkObject

@enduml
