@startuml savePackageClassDiagram

package Save{
class SaveGame {
    - mFileName : string
    - mFields : vector<SaveField>
    - mArrays : vector<SaveArray>
    + SaveGame(const string &aFileName)
    + store() : void
    + remove() : void
    + addField(string aName, string aValue) : void
    + setField(string aName, string aValue) : void
    + getField(string aName) : SaveField&
    + getField(string aName) : string
    + addArray(string aName) : void
    + setArray(string aName, SaveArray value) : void
    + getArray(string aName) : SaveArray&
}

class SaveField {
    - mName : string
    - mValue : string
    + SaveField(string aName)
    + getName() : string
    + setValue(string aValue) : void
    + getValue() : string
}

class SaveArray {
    - mName : string
    - mFields : vector<SaveField>
    + SaveArray(string aName)
    + getName() : string
    + addField(string aName, string aValue) : void
    + setField(string aName, string aValue) : void
    + getField(string aName) : string
}

SaveGame *-- "*" SaveField
SaveGame *-- "*" SaveArray
SaveArray *-- "*" SaveField
}

Save *-- "*" SaveGame



' class SaveGameUtil {
'   + isInteger(string aValue) : static bool
'   + isFloat(string aValue) : static bool
' }

' together {
' class IntSaveField {
'   - mName : string
'   - mValue : int

'   + SaveField(string name)

'   + getName() : string

'   + setValue(int) : void
'   + getValue() : int
' }

' class FloatSaveField {
'   - mName : string
'   - mValue : float

'   + SaveField(string name)

'   + getName() : string

'   + setValue(float) : void
'   + getValue() : float
' }

' class StringSaveField {
'   - mName : string
'   - mValue : string

'   + SaveField(string name)

'   + getName() : string

'   + setValue(string) : void
'   + getValue() : string
' }
' }

' SaveGame *-- "*" SaveField
' SaveGame *-- "*" SaveArray
' SaveArray *-- "*" SaveField


' EngineBravo *--"1" SaveGameManager

' SaveGameManager *--"*" SaveGame

' SaveGame <-left- SaveGameUtil
' SaveGame *--"*" SaveArray
' SaveGame -[hidden]> SaveArray
' SaveGame *--"*" IntSaveField
' SaveGame *--"*" FloatSaveField
' SaveGame *--"*" StringSaveField

' SaveArray <-up- SaveGameUtil
' SaveArray *--"*" IntSaveField
' SaveArray *--"*" FloatSaveField
' SaveArray *--"*" StringSaveField
@enduml