#ifndef NETWORKINFORMATION_H
#define NETWORKINFORMATION_H

#define SERVER_PORT 60001
#define CLIENT_PORT 60002

enum class NetworkRole { UNASSIGNED, CLIENT, SERVER, HOST };

#endif // NETWORKINFORMATION_H